#!/bin/sh /etc/rc.common

 
START=11

start() {        
    echo "LTE qmi start..."
    /usr/share/ed-qmi/lte-reconnect.sh
    # commands to launch application
}                 


stop() {
    echo stop...
    killall quectel-CM
    killall lte-reconnect.sh
}
